name: Deployment
on:
  push:
    branches:
      - main
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Start Next.js server
        run: |
          npm start &
          npx wait-on http://127.0.0.1:3000  # Ensure the server is ready
      - name: Run tests
        run: npm test --if-present
